### PR TITLE
gcc compilation support.

### PR DESCRIPTION
**Pull request by balrog-kun**
Just a basic compilation under Linux:
$ cd gcc
$ make
$ st-flash write /dev/sg0 h8mini 0x08000000

### CODE REVIEW

**Comment by silver13** [comment]
I added this, thank you for your work.

Just one thing, why make volatile in delay?

Also , what name for credit?

**Comment by silver13** [comment]
I wonder if DEFS = -DUSE_STDPERIPH_DRIVER shoud be DEFS = -D USE_STDPERIPH_DRIVER

**Comment by silver13** [comment]
I figured out why it's so big, it is because it links the unused functions such as softi2c.c
Not sure how to fix it, I think it needs some sort of 2 pass or to strip the unused functions somehow.

**Comment by balrog-kun** [comment]
I will look into that later, there must be some linker option to discard all the unused code because many projects do that.

As for the volatile, it's to prevent the delay loop from being optimized away.  It just tells the compiler that the variable really needs to be assigned all the values from 16 \* delay down to 0 even though it's unused.  I guess it's still free to do things like loop unrolling but we don't care as long as it steps through all the values.

AFAIK the -DXYZ and -D XYZ are equivalent so this should be ok.

For credit you can put balrog-kun or if you use the git merge or github merge button it preserves metadata (names, dates..)

**Comment by silver13** [comment]
I added some switches that should fix it

**Comment by balrog-kun** [comment]
Thanks, I now get a 20k binary (had come up with the same sections discard switches), is this similar to what you get with Keil?
Will you integrate this into h8mini-testing or would you like a pull request?

**Comment by silver13** [comment]
the keil binary is smaller, but it uses some nonstandard lib "MicroLib". without that it's 15k (with it it's 12)
I can integrate it in level mode (if it fits). But if you find better optimizations, let me know , as I an not accustomed with makefiles, so I will not look into it a lot more. It's actually surprising I managed to compile it on windows.

**Pull request closed without merging**
